"use client";

import { usePathname } from "next/navigation";
import { Language, useLanguage } from "./i18n";
import SiteFooter from "./site-footer";
import UpcomingTournament from "./upcoming-tournament";

type Sport = "tennis" | "padel";
type SportCopy = { eyebrow: string; titleA: string; titleB: string; intro: string; approach: string; kicker: string; approachTitle: string; approachText: string; experience: string; experienceTitle: string; points: [string, string][]; liveLabel: string; liveTitle: string; liveText: string; visual: string };

const copy: Record<Sport, Record<Language, SportCopy>> = {
  tennis: {
    en: { eyebrow: "KYNG CUP Tennis · Vienna", titleA: "More than", titleB: "a game", intro: "Tournament-level competition. A community built around sport, ambition and the people you want to meet again.", approach: "Our approach", kicker: "Not just a tournament", approachTitle: "The level of competition. The ease of belonging.", approachText: "KYNG CUP Tennis brings together committed players through a format that respects the match and everything around it.", experience: "The tennis experience", experienceTitle: "Built for the match. Remembered for the atmosphere.", points: [["Competition with respect", "Strong opponents, fair judging and a format that respects every level."], ["Details that feel effortless", "Clear schedules, quality courts, new balls and a team that stays present."], ["A community beyond the court", "New rivals become familiar faces, useful contacts and lasting friends."]], liveLabel: "Live tennis", liveTitle: "Follow every match.", liveText: "See the full tennis draw, match times, courts and live results as every pair moves toward the final.", visual: "Play seriously. Feel at home." },
    uk: { eyebrow: "KYNG CUP Tennis · Відень", titleA: "Більше ніж", titleB: "гра", intro: "Змагання турнірного рівня. Спільнота, побудована навколо спорту, амбіцій і людей, яких хочеться зустріти знову.", approach: "Наш підхід", kicker: "Не просто турнір", approachTitle: "Рівень конкуренції. Легкість приналежності.", approachText: "KYNG CUP Tennis об’єднує відданих гравців у форматі, що поважає матч і все, що відбувається навколо нього.", experience: "Тенісний досвід", experienceTitle: "Створено для матчу. Запам’ятовується атмосферою.", points: [["Змагання з повагою", "Сильні суперники, чесне суддівство та формат, що поважає кожен рівень."], ["Деталі без зайвих зусиль", "Зрозумілий розклад, якісні корти, нові м’ячі та команда поруч."], ["Спільнота за межами корту", "Нові суперники стають знайомими обличчями, корисними контактами й друзями."]], liveLabel: "Теніс наживо", liveTitle: "Стежте за кожним матчем.", liveText: "Дивіться повну сітку, час матчів, корти й результати наживо на шляху кожної пари до фіналу.", visual: "Грайте серйозно. Почувайтеся як удома." },
    de: { eyebrow: "KYNG CUP Tennis · Wien", titleA: "Mehr als", titleB: "ein Spiel", intro: "Wettbewerb auf Turnierniveau. Eine Community rund um Sport, Ehrgeiz und Menschen, die man wiedersehen möchte.", approach: "Unser Ansatz", kicker: "Mehr als ein Turnier", approachTitle: "Das Niveau des Wettbewerbs. Die Leichtigkeit des Dazugehörens.", approachText: "KYNG CUP Tennis bringt engagierte Spieler in einem Format zusammen, das das Match und alles darum respektiert.", experience: "Das Tennis-Erlebnis", experienceTitle: "Für das Match gemacht. Für die Atmosphäre erinnert.", points: [["Wettbewerb mit Respekt", "Starke Gegner, faire Spielleitung und ein Format für jedes Niveau."], ["Details, die leicht wirken", "Klare Zeitpläne, gute Courts, neue Bälle und ein präsentes Team."], ["Community über den Court hinaus", "Aus neuen Rivalen werden bekannte Gesichter, wertvolle Kontakte und Freunde."]], liveLabel: "Tennis live", liveTitle: "Verfolge jedes Match.", liveText: "Sieh den vollständigen Turnierbaum, Matchzeiten, Courts und Live-Ergebnisse bis zum Finale.", visual: "Ernsthaft spielen. Zuhause fühlen." },
    ru: { eyebrow: "KYNG CUP Tennis · Вена", titleA: "Больше чем", titleB: "игра", intro: "Соревнование турнирного уровня. Сообщество вокруг спорта, амбиций и людей, которых хочется встретить снова.", approach: "Наш подход", kicker: "Не просто турнир", approachTitle: "Уровень конкуренции. Лёгкость принадлежности.", approachText: "KYNG CUP Tennis объединяет увлечённых игроков в формате, который уважает матч и всё, что происходит вокруг него.", experience: "Теннисный опыт", experienceTitle: "Создано для матча. Запоминается атмосферой.", points: [["Соревнование с уважением", "Сильные соперники, честное судейство и формат для каждого уровня."], ["Детали без лишних усилий", "Понятное расписание, качественные корты, новые мячи и команда рядом."], ["Сообщество за пределами корта", "Новые соперники становятся знакомыми лицами, полезными контактами и друзьями."]], liveLabel: "Теннис в эфире", liveTitle: "Следите за каждым матчем.", liveText: "Смотрите полную сетку, время матчей, корты и результаты в реальном времени на пути каждой пары к финалу.", visual: "Играйте серьёзно. Чувствуйте себя как дома." },
  },
  padel: {
    en: { eyebrow: "KYNG CUP Padel · Vienna", titleA: "Built for", titleB: "the rally", intro: "Fast decisions, shared instinct and a court that brings everyone closer. Padel turns competition into immediate connection.", approach: "Our approach", kicker: "Closer court. Bigger energy.", approachTitle: "Four players. One rhythm. A community in motion.", approachText: "KYNG CUP Padel pairs competitive structure with the social energy of the game: quick exchanges, smart teamwork and an atmosphere that never sits still.", experience: "The padel experience", experienceTitle: "Play off the glass. Trust your partner. Stay for the people.", points: [["Partnership under pressure", "A format that rewards communication, positioning and shared decisions."], ["Fast, clear tournament flow", "Short transitions, visible schedules and courts that stay full of energy."], ["Social by design", "A compact court makes every point easier to watch, share and remember."]], liveLabel: "Live padel", liveTitle: "Every rally. Every result.", liveText: "Follow the padel draw, match times, courts and live results from the opening round to the champions.", visual: "Play together. Move as one." },
    uk: { eyebrow: "KYNG CUP Padel · Відень", titleA: "Створено для", titleB: "розіграшу", intro: "Швидкі рішення, спільний інстинкт і корт, що зближує всіх. Падел перетворює змагання на миттєвий зв’язок.", approach: "Наш підхід", kicker: "Ближчий корт. Більша енергія.", approachTitle: "Четверо гравців. Один ритм. Спільнота в русі.", approachText: "KYNG CUP Padel поєднує змагальну структуру із соціальною енергією гри: швидкі обміни, розумна командна робота та жива атмосфера.", experience: "Досвід паделу", experienceTitle: "Грайте від скла. Довіряйте партнеру. Залишайтеся заради людей.", points: [["Партнерство під тиском", "Формат, що винагороджує комунікацію, позиціонування та спільні рішення."], ["Швидкий і зрозумілий турнір", "Короткі переходи, видимий розклад і корти, сповнені енергії."], ["Соціальність у самій грі", "Компактний корт робить кожен розіграш легшим для перегляду й спільних емоцій."]], liveLabel: "Падел наживо", liveTitle: "Кожен розіграш. Кожен результат.", liveText: "Стежте за сіткою паделу, часом матчів, кортами й результатами від першого раунду до чемпіонів.", visual: "Грайте разом. Рухайтеся як одне ціле." },
    de: { eyebrow: "KYNG CUP Padel · Wien", titleA: "Gemacht für", titleB: "den Ballwechsel", intro: "Schnelle Entscheidungen, gemeinsamer Instinkt und ein Court, der alle näher zusammenbringt. Padel macht aus Wettbewerb sofortige Verbindung.", approach: "Unser Ansatz", kicker: "Näherer Court. Mehr Energie.", approachTitle: "Vier Spieler. Ein Rhythmus. Eine Community in Bewegung.", approachText: "KYNG CUP Padel verbindet sportliche Struktur mit der sozialen Energie des Spiels: schnelle Wechsel, kluges Teamwork und eine Atmosphäre, die nie stillsteht.", experience: "Das Padel-Erlebnis", experienceTitle: "Über das Glas spielen. Dem Partner vertrauen. Für die Menschen bleiben.", points: [["Partnerschaft unter Druck", "Ein Format, das Kommunikation, Positionierung und gemeinsame Entscheidungen belohnt."], ["Schneller, klarer Turnierfluss", "Kurze Wechsel, sichtbare Zeitpläne und Courts voller Energie."], ["Von Natur aus sozial", "Der kompakte Court macht jeden Punkt leichter zu verfolgen, zu teilen und zu erinnern."]], liveLabel: "Padel live", liveTitle: "Jeder Ballwechsel. Jedes Ergebnis.", liveText: "Verfolge Turnierbaum, Matchzeiten, Courts und Live-Ergebnisse von der ersten Runde bis zu den Champions.", visual: "Zusammen spielen. Als Einheit bewegen." },
    ru: { eyebrow: "KYNG CUP Padel · Вена", titleA: "Создано для", titleB: "розыгрыша", intro: "Быстрые решения, общий инстинкт и корт, который сближает всех. Падел превращает соревнование в мгновенную связь.", approach: "Наш подход", kicker: "Ближе корт. Больше энергии.", approachTitle: "Четыре игрока. Один ритм. Сообщество в движении.", approachText: "KYNG CUP Padel сочетает соревновательную структуру с социальной энергией игры: быстрые обмены, умная командная работа и живая атмосфера.", experience: "Опыт падела", experienceTitle: "Играйте от стекла. Доверяйте партнёру. Оставайтесь ради людей.", points: [["Партнёрство под давлением", "Формат, который вознаграждает общение, позиционирование и совместные решения."], ["Быстрый и понятный турнир", "Короткие переходы, наглядное расписание и корты, полные энергии."], ["Социальность в самой игре", "Компактный корт делает каждый розыгрыш удобным для просмотра и общих эмоций."]], liveLabel: "Падел в эфире", liveTitle: "Каждый розыгрыш. Каждый результат.", liveText: "Следите за сеткой падела, временем матчей, кортами и результатами от первого раунда до чемпионов.", visual: "Играйте вместе. Двигайтесь как одно целое." },
  },
};

export default function SportPage({ sport }: { sport: Sport }) {
  const pathname = usePathname();
  const basePath = pathname.startsWith("/kyng-cup") ? "/kyng-cup" : "";
  const { language, t } = useLanguage();
  const c = copy[sport][language];
  return <main className={`sport-page ${sport}-page`}>
    <section className={`hero sport-hero ${sport}-hero`}><div className="hero-copy"><p className="eyebrow">{c.eyebrow}</p><h1>{c.titleA}<br />{c.titleB}<span className="accent-dot">.</span></h1><p className="hero-intro">{c.intro}</p></div></section>
    <section className="manifesto"><div className="section-index"><span>01</span><span>{c.approach}</span></div><div className="manifesto-copy"><p className="kicker">{c.kicker}</p><h2>{c.approachTitle}</h2><p className="manifesto-lead">{c.approachText}</p></div><div className="principle-card"><span className="principle-number">100%</span><p>KYNG CUP</p></div></section>
    <section className="experience"><div className="experience-visual" role="img" aria-label={`${sport} player in motion`}><div className="visual-label"><span>KYNG standard</span><strong>{c.visual}</strong></div></div><div className="experience-copy"><div className="section-index light"><span>02</span><span>{c.experience}</span></div><h2>{c.experienceTitle}</h2><div className="experience-list">{c.points.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
    <UpcomingTournament sport={sport} />
    <section className="home-bracket-cta"><div className="home-bracket-copy"><div className="section-index"><span>04</span><span>{c.liveLabel}</span></div><span className="home-live-label"><i />{t("live")}</span><h2>{c.liveTitle}</h2><p>{c.liveText}</p><div className="home-bracket-actions"><a href={`${basePath}/bracket/?sport=${sport}`}>{t("openBracket")} ↗</a><button type="button">{t("participate")}</button></div></div><div className="home-bracket-preview" aria-hidden="true"><div className="preview-round-labels"><span>Quarterfinal</span><span>Semifinal</span><span>Final</span></div><div className="preview-bracket-grid"><div className="preview-column"><div className="preview-match"><i className="preview-connector" /><span><b>01</b> Vienna Pair</span><span><b>08</b> King&apos;s Court</span></div><div className="preview-match"><i className="preview-connector" /><span><b>04</b> Clay Club</span><span><b>05</b> Match Point</span></div><div className="preview-match"><i className="preview-connector" /><span><b>02</b> Centre Court</span><span><b>07</b> Net Society</span></div><div className="preview-match"><i className="preview-connector" /><span><b>03</b> Grandstand</span><span><b>06</b> The Racquets</span></div></div><div className="preview-column preview-middle"><div className="preview-match"><i className="preview-connector" /><span><b>01</b> Vienna Pair</span><span><b>04</b> Clay Club</span></div><div className="preview-match"><i className="preview-connector" /><span><b>02</b> Centre Court</span><span><b>03</b> Grandstand</span></div></div><div className="preview-column preview-final"><div className="preview-match"><i className="preview-connector" /><small>Final · Centre court</small><span><b>01</b> Vienna Pair</span><span><b>02</b> Centre Court</span></div></div></div></div></section>
    <SiteFooter />
  </main>;
}
