"use client";

import { usePathname } from "next/navigation";
import { Language, useLanguage } from "./i18n";
import SiteFooter from "./site-footer";
import UpcomingTournament from "./upcoming-tournament";

type Sport = "tennis" | "padel";
type SportCopy = { eyebrow: string; titleA: string; titleB: string; intro: string; approach: string; kicker: string; approachTitle: string; approachText: string; experience: string; experienceTitle: string; points: [string, string][]; liveLabel: string; liveTitle: string; liveText: string; visual: string };

const copy: Record<Sport, Record<Language, SportCopy>> = {
  tennis: {
    en: { eyebrow: "KYNG CUP Tennis · Vienna", titleA: "More than", titleB: "a game", intro: "Tournament-level competition. A community built around sport, ambition and the people you want to meet again.", approach: "Our approach", kicker: "Not just a tournament", approachTitle: "Strong competition. A community worth returning to.", approachText: "KYNG CUP Tennis brings committed players together for well-organised matches, strong opponents and an experience that extends beyond the court.", experience: "The tennis experience", experienceTitle: "The match is only part of the experience.", points: [["The level", "Strong players. Real competition. Mutual respect."], ["The standard", "Every detail considered. Nothing left to chance."], ["The community", "Connections that begin on the court and continue beyond it."]], liveLabel: "Live tennis", liveTitle: "Follow every match.", liveText: "See the full tennis draw, match times, courts and live results as every pair moves toward the final.", visual: "Play seriously. Feel at home." },
    uk: { eyebrow: "KYNG CUP Tennis · Відень", titleA: "Більше ніж", titleB: "гра", intro: "Змагання турнірного рівня. Спільнота, побудована навколо спорту, амбіцій і людей, яких хочеться зустріти знову.", approach: "Наш підхід", kicker: "Не просто турнір", approachTitle: "Сильні суперники. Спільнота, до якої хочеться повертатися.", approachText: "KYNG CUP Tennis об’єднує відданих гравців заради добре організованих матчів, сильних суперників і досвіду, що виходить за межі корту.", experience: "Тенісний досвід", experienceTitle: "Матч — лише частина досвіду.", points: [["Рівень", "Сильні гравці. Справжня конкуренція. Взаємна повага."], ["Стандарт", "Кожна деталь продумана. Нічого не залишено напризволяще."], ["Спільнота", "Зв’язки, що починаються на корті й продовжуються за його межами."]], liveLabel: "Теніс наживо", liveTitle: "Стежте за кожним матчем.", liveText: "Дивіться повну сітку, час матчів, корти й результати наживо на шляху кожної пари до фіналу.", visual: "Грайте серйозно. Почувайтеся як удома." },
    de: { eyebrow: "KYNG CUP Tennis · Wien", titleA: "Mehr als", titleB: "ein Spiel", intro: "Wettkampf auf Turnierniveau. Eine Community rund um Sport, Ehrgeiz und Menschen, denen man gern wieder begegnet.", approach: "Unser Ansatz", kicker: "Mehr als ein Turnier", approachTitle: "Starke Gegner. Eine Community, zu der man gern zurückkehrt.", approachText: "KYNG CUP Tennis bringt engagierte Spieler zu gut organisierten Matches, starken Gegnern und einem Erlebnis zusammen, das über den Court hinausgeht.", experience: "Das Tenniserlebnis", experienceTitle: "Das Match ist nur ein Teil des Erlebnisses.", points: [["Das Niveau", "Starke Spieler. Echter Wettbewerb. Gegenseitiger Respekt."], ["Der Standard", "Jedes Detail durchdacht. Nichts dem Zufall überlassen."], ["Die Community", "Verbindungen, die auf dem Court beginnen und darüber hinaus weiterleben."]], liveLabel: "Tennis live", liveTitle: "Verfolge jedes Match.", liveText: "Sieh den vollständigen Turnierbaum, Matchzeiten, Courts und Live-Ergebnisse auf dem Weg jedes Teams ins Finale.", visual: "Ernsthaft spielen. Sich zuhause fühlen." },
    ru: { eyebrow: "KYNG CUP Tennis · Вена", titleA: "Больше чем", titleB: "игра", intro: "Соревнование турнирного уровня. Сообщество вокруг спорта, амбиций и людей, которых хочется встретить снова.", approach: "Наш подход", kicker: "Не просто турнир", approachTitle: "Сильные соперники. Сообщество, к которому хочется возвращаться.", approachText: "KYNG CUP Tennis объединяет увлечённых игроков ради хорошо организованных матчей, сильных соперников и опыта, который продолжается за пределами корта.", experience: "Теннисный опыт", experienceTitle: "Матч — лишь часть опыта.", points: [["Уровень", "Сильные игроки. Настоящая конкуренция. Взаимное уважение."], ["Стандарт", "Каждая деталь продумана. Ничего не оставлено на волю случая."], ["Сообщество", "Связи, которые начинаются на корте и продолжаются за его пределами."]], liveLabel: "Теннис в эфире", liveTitle: "Следите за каждым матчем.", liveText: "Смотрите полную сетку, время матчей, корты и результаты в реальном времени на пути каждой пары к финалу.", visual: "Играйте серьёзно. Чувствуйте себя как дома." },
  },
  padel: {
    en: { eyebrow: "KYNG CUP Padel · Vienna", titleA: "Built for", titleB: "the rally", intro: "Fast decisions, shared instinct and a court that brings people closer. Padel creates connection from the first rally.", approach: "Our approach", kicker: "Fast game. Shared rhythm.", approachTitle: "Four players. One rhythm. A community in motion.", approachText: "KYNG CUP Padel pairs competitive structure with the social energy of the game: quick exchanges, smart teamwork and an atmosphere that never sits still.", experience: "The padel experience", experienceTitle: "The match is only part of the experience.", points: [["The level", "Strong players. Real competition. Mutual respect."], ["The standard", "Every detail considered. Nothing left to chance."], ["The community", "Connections that begin on the court and continue beyond it."]], liveLabel: "Live padel", liveTitle: "Every rally. Every result.", liveText: "Follow the padel draw, match times, courts and live results from the opening round to the final point.", visual: "Play together. Move as one." },
    uk: { eyebrow: "KYNG CUP Padel · Відень", titleA: "Створено для", titleB: "розіграшу", intro: "Швидкі рішення, спільний інстинкт і корт, що зближує людей. У паделі зв’язок виникає вже з першого розіграшу.", approach: "Наш підхід", kicker: "Швидка гра. Спільний ритм.", approachTitle: "Четверо гравців. Один ритм. Спільнота в русі.", approachText: "KYNG CUP Padel поєднує змагальну структуру із соціальною енергією гри: швидкі обміни, розумна командна робота та жива атмосфера.", experience: "Досвід паделу", experienceTitle: "Матч — лише частина досвіду.", points: [["Рівень", "Сильні гравці. Справжня конкуренція. Взаємна повага."], ["Стандарт", "Кожна деталь продумана. Нічого не залишено напризволяще."], ["Спільнота", "Зв’язки, що починаються на корті й продовжуються за його межами."]], liveLabel: "Падел наживо", liveTitle: "Кожен розіграш. Кожен результат.", liveText: "Стежте за сіткою паделу, часом матчів, кортами й результатами від першого раунду до фінального розіграшу.", visual: "Грайте разом. Рухайтеся як одне ціле." },
    de: { eyebrow: "KYNG CUP Padel · Wien", titleA: "Gemacht für", titleB: "den Ballwechsel", intro: "Schnelle Entscheidungen, gemeinsamer Instinkt und ein Court, der Menschen näher zusammenbringt. Beim Padel entsteht Verbindung schon mit dem ersten Ballwechsel.", approach: "Unser Ansatz", kicker: "Schnelles Spiel. Gemeinsamer Rhythmus.", approachTitle: "Vier Spieler. Ein Rhythmus. Eine Community in Bewegung.", approachText: "KYNG CUP Padel verbindet eine klare Turnierstruktur mit der sozialen Energie des Spiels: schnelle Ballwechsel, kluges Zusammenspiel und eine lebendige Atmosphäre.", experience: "Das Padelerlebnis", experienceTitle: "Das Match ist nur ein Teil des Erlebnisses.", points: [["Das Niveau", "Starke Spieler. Echter Wettbewerb. Gegenseitiger Respekt."], ["Der Standard", "Jedes Detail durchdacht. Nichts dem Zufall überlassen."], ["Die Community", "Verbindungen, die auf dem Court beginnen und darüber hinaus weiterleben."]], liveLabel: "Padel live", liveTitle: "Jeder Ballwechsel. Jedes Ergebnis.", liveText: "Verfolge Turnierbaum, Matchzeiten, Courts und Live-Ergebnisse von der ersten Runde bis zum letzten Punkt.", visual: "Gemeinsam spielen. Als Einheit bewegen." },
    ru: { eyebrow: "KYNG CUP Padel · Вена", titleA: "Создано для", titleB: "розыгрыша", intro: "Быстрые решения, общий инстинкт и корт, который сближает людей. В паделе связь возникает уже с первого розыгрыша.", approach: "Наш подход", kicker: "Быстрая игра. Общий ритм.", approachTitle: "Четыре игрока. Один ритм. Сообщество в движении.", approachText: "KYNG CUP Padel сочетает соревновательную структуру с социальной энергией игры: быстрые обмены, умная командная работа и живая атмосфера.", experience: "Опыт падела", experienceTitle: "Матч — лишь часть опыта.", points: [["Уровень", "Сильные игроки. Настоящая конкуренция. Взаимное уважение."], ["Стандарт", "Каждая деталь продумана. Ничего не оставлено на волю случая."], ["Сообщество", "Связи, которые начинаются на корте и продолжаются за его пределами."]], liveLabel: "Падел в эфире", liveTitle: "Каждый розыгрыш. Каждый результат.", liveText: "Следите за сеткой падела, временем матчей, кортами и результатами от первого раунда до финального розыгрыша.", visual: "Играйте вместе. Двигайтесь как одно целое." },
  },
};

export default function SportPage({ sport }: { sport: Sport }) {
  const pathname = usePathname();
  const basePath = pathname.startsWith("/kyng-cup") ? "/kyng-cup" : "";
  const { language, t } = useLanguage();
  const c = copy[sport][language];
  return <main className={`sport-page ${sport}-page`}>
    <section className={`hero sport-hero ${sport}-hero`}><div className="hero-copy"><p className="eyebrow">{c.eyebrow}</p><h1>{c.titleA}<br />{c.titleB}<span className="accent-dot">.</span></h1><p className="hero-intro">{c.intro}</p></div></section>
    <section className="manifesto"><div className="section-index"><span>01</span><span>{c.approach}</span></div><div className="manifesto-copy"><p className="kicker">{c.kicker}</p><h2>{c.approachTitle}</h2><p className="manifesto-lead">{c.approachText}</p></div><div className="principle-ball" aria-hidden="true" /></section>
    <section className="experience"><div className="experience-visual" role="img" aria-label={`${sport} player in motion`}><div className="visual-label"><span>KYNG standard</span><strong>{c.visual}</strong></div></div><div className="experience-copy"><div className="section-index light"><span>02</span><span>{c.experience}</span></div><h2>{c.experienceTitle}</h2><div className="experience-list">{c.points.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
    <UpcomingTournament sport={sport} />
    <section className="home-bracket-cta"><div className="home-bracket-copy"><div className="section-index"><span>04</span><span>{c.liveLabel}</span></div><span className="home-live-label"><i />{t("live")}</span><h2>{c.liveTitle}</h2><p>{c.liveText}</p><div className="home-bracket-actions"><a href={`${basePath}/bracket/?sport=${sport}`}>{t("openBracket")} ↗</a><button type="button">{t("participate")}</button></div></div><div className="home-bracket-preview" aria-hidden="true"><div className="preview-round-labels"><span>Quarterfinal</span><span>Semifinal</span><span>Final</span></div><div className="preview-bracket-grid"><div className="preview-column"><div className="preview-match"><i className="preview-connector" /><span><b>01</b> Vienna Pair</span><span><b>08</b> King&apos;s Court</span></div><div className="preview-match"><i className="preview-connector" /><span><b>04</b> Clay Club</span><span><b>05</b> Match Point</span></div><div className="preview-match"><i className="preview-connector" /><span><b>02</b> Centre Court</span><span><b>07</b> Net Society</span></div><div className="preview-match"><i className="preview-connector" /><span><b>03</b> Grandstand</span><span><b>06</b> The Racquets</span></div></div><div className="preview-column preview-middle"><div className="preview-match"><i className="preview-connector" /><span><b>01</b> Vienna Pair</span><span><b>04</b> Clay Club</span></div><div className="preview-match"><i className="preview-connector" /><span><b>02</b> Centre Court</span><span><b>03</b> Grandstand</span></div></div><div className="preview-column preview-final"><div className="preview-match"><i className="preview-connector" /><small>Final · Centre court</small><span><b>01</b> Vienna Pair</span><span><b>02</b> Centre Court</span></div></div></div></div></section>
    <SiteFooter />
  </main>;
}
